[#-------------- INCLUDES AND ASSIGNMENTS --------------]
[#include "macros/breadcrumb.ftl"]
[#include "macros/productTeaserList.ftl"]
[#include "macros/productFilters.ftl"]

[#assign categoryId = (ctx.getParameter("categoryId")?html)!content.categoryId?split("--")?reverse[0]!""]
[#assign currentPage = (ctx.getParameter("currentPage")?number)!1]
[#assign perPage = (content.perPage?number)!20]
[#assign productTypes = ctfn.getProductTypes()]
[#assign attributeFacets = (content.attributeFacets)![]]
[#assign filterBy = ctfn.getFilterBy(attributeFacets)]

[#if perPage == 0]
    [#-- set max limit value--]
    [#assign perPage = 500]
[/#if]

[#-------------- RENDERING --------------]
[#if categoryId?has_content]
    [#assign products = ctfn.getProducts(categoryId, (currentPage-1)*perPage, perPage, productTypes, attributeFacets, filterBy)!]
    [@breadcrumb ctfn.getCategory(categoryId) cmsfn.link(cmsfn.page(content)) /]
    [#if products.getFacetsResults()?has_content]
        [@productFilters attributeFacets products.getFacetsResults() productTypes filterBy /]
    [/#if]
    [#if products.getResults()?has_content]
        [@productTeaserList products currentPage perPage content.productDetailPage /]
    [/#if]
[/#if]
