[#-------------- INCLUDES AND ASSIGNMENTS --------------]
[#include "macros/productTeaserList.ftl"]

[#assign queryStr = (ctx.getParameter("queryStr")?html)!""]
[#assign currentPage = (ctx.getParameter("currentPage")?number)!1]
[#assign perPage = (content.perPage?number)!20]
[#if perPage == 0]
    [#-- set max limit value--]
    [#assign perPage = 500]
[/#if]

[#-------------- RENDERING --------------]
[#if queryStr?has_content]
    [#assign products = ctfn.searchForProducts(queryStr, (currentPage-1)*perPage, perPage)!]
    [#if products.getResults()?has_content]
        [@productTeaserList products currentPage perPage content.productDetailPage /]
    [#else]
        ${i18n['ct.noResultsFound']}
    [/#if]
[/#if]
